# Generated by Django 4.1.1 on 2022-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_de_afiliado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Autorizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_a_realizar', models.CharField(max_length=30)),
                ('numero_de_afiliado', models.EmailField(max_length=254)),
                ('fecha_de_orden', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro_al_viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_afiliado', models.EmailField(max_length=254)),
                ('plan', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
            ],
        ),
    ]
