# Generated by Django 4.1.1 on 2022-11-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_plan_alter_autorizaciones_numero_de_afiliado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Afiliado',
        ),
        migrations.DeleteModel(
            name='Empadronamiento',
        ),
    ]
